export const CATEGORIES_ACTION_TYPES = {
    FETCH_CATEGORIES_START_START: 'category/SET_CATEGORIES_START',
    FETCH_CATEGORIES_START_SUCCESS: 'category/SET_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_START_FAILED: 'category/SET_CATEGORIES_FAILED',
}